# Nijika Deablr Minecraft Server

services:
  mc:
    image: itzg/minecraft-server:latest
    container_name: nijika-deablr-mc
    tty: true
    stdin_open: true
    restart: unless-stopped
    # No host port binding; mc-router handles external routing on 25565
    networks:
      - dokploy-network
    environment:
      EULA: "TRUE"
      TYPE: "PAPER"
      VERSION: "26.1.2"
      MEMORY: "2048M"
      MOTD: "A server for us"
      ICON: "/server-icon.png"
      FORCE_GAMEMODE: "true"
      ENABLE_COMMAND_BLOCK: "true"
      SPAWN_PROTECTION: "0"
      OPS: |-
        c1c43a34-eea1-44a6-8676-7f08b942939a
      PLUGINS: |-
        https://hangarcdn.papermc.io/plugins/EngineHub/WorldEdit/versions/7.4.2/PAPER/worldedit-bukkit-7.4.2.jar
      HIDE_ONLINE_PLAYERS: "true"
      ENFORCE_SECURE_PROFILE: "false"
      SERVER_NAME: "Nijika Deablr Server"
    volumes:
      - "/opt/nijika-deablr/data:/data"
      - "./server-icon.png:/server-icon.png:ro"

networks:
  dokploy-network:
    external: true
